services:
  frontend:
    build: ./frontend
    image: d2d-frontend
    command: ["http-server", "dist", "--port", "80"]
    ports:
      - "80:80"
  backend:
    build: ./backend-express
    image: d2d-api
    command: ["node", "./build/index.js"]
    ports:
      - "9000:9000"
    depends_on:
      - "db"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: d2d_db
    volumes:
      - ./backend-express/mysql_data:/var/lib/mysql

