services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: d2d_db
    volumes:
      - $HOME/Desktop/mysql-data:/var/lib/mysql

