services:
  backend:
    build: .
    image: d2d-api
    command: ["uvicorn", "d2d.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1